var stepFormData = {
  // StepWorkload
  Workloads: [],
  Versions: [],
  selectedVersion: '',
  // StepHost
  MachineControllers: [],
  selectedController: '',
  MachineWorkers: [],
  selectedWorker: '',
  selectedDatetime: null,
  tableData: null,
  checkGreen: false,
  checkRed: false,
  // StepKubernetes
  deploy_kubernetes: false,
  KubernetesInstallMethod: [],
  selectedKubernetesInstallMethod: { value: '' },
  KubernetesVersion: [],
  selectedKubernetesVersion: { value: '' },
  KubernetesNetworkPlugin: [],
  selectedKubernetesNetworkPlugin: { value: '' },
  ContainerManager: [],
  selectedContainerManager: { value: '' },
  DashboardEnable: [],
  selectedDashboardEnable: { value: 'false' },
  HEMLEnable: [],
  selectedHEMLEnable: { value: 'false' },
  RegistryEnable: [],
  selectedRegistryEnable: { value: 'false' },
  IngressNginxEnabled: [],
  selectedIngressNginxEnabled: { value: 'false' },
  IngressNginxHostNetwork: [],
  selectedIngressNginxHostNetwork: { value: 'false' },
  KrewEnabled: [],
  selectedKrewEnabled: { value: 'false' },
  // StepWorkloadArgs
  deploy_workload_args: true,
  jenkins_args: true,
  workload_package_args: false,
  WorkloadName: [],
  selectedWorkloadName: { name: '' },
  JSFRepo: [],
  selectedJSFRepo: '',
  Commit: [],
  selectedCommit: '',
  Registry: [],
  selectedRegistry: { value: '' },
  selectedCaseFilter: '',
  selectedWorkloadParameter: '',
  // DeployMode: [],
  // selectedDeployMode: '',
  // TaskPath: [],
  // selectedTaskPath: '',
  // PSFRepo: [],
  // selectedPSFRepo: '',
  // WorkloadArgs: [],
  // selectedWorkloadArgs: '',
  // StepSoftwareArgs
  software_package_args: false,
  DPDK: false,
  selectedDPDKArgs: '',
  // StepSystermArgs
  system_deploy_args: false,
  os_update: false,
  kernel_update: false,
  kernel_args_update: false,
  bios_update: false,
  OS: [],
  selectedOS: { value: '' },
  KernelVersion: [],
  selectedKernelVersion: { value: '' },
  KernelArgs: [],
  selectedKernelArgs: { value: '' },
  BIOSArgs: [],
  selectedBIOSArgs: [],
  BIOSArgsMapping: {},
  // StepVMArgs
  vm_deploy_args: false,
  VMDocker: [],
  selectedVMDocker: { value: '' },
  OSNumber: [],
  selectedOSNumber: { value: '' },
  OSType: [],
  selectedOSType: { value: '' },
  VMName: [],
  selectedVMName: '',
  Memory: [],
  selectedMemory: { value: '' },
  CPUNumber: [],
  selectedCPUNumber: { value: '' },
  Disk: [],
  selectedDisk: { value: '' },
  // StepEmail
  SenderEmail: '',
  ReceiverEmail: ''
}
export default stepFormData
