# Generated by Django 3.1.1 on 2022-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_component_componentparam_componentversion_workload_workloadcomponentversion_workloadsystemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadsystemconfig',
            name='workload_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='workload id'),
        ),
    ]
