# Generated by Django 3.1.1 on 2022-03-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20220324_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='deploy_mode',
        ),
    ]
