# Generated by Django 3.1.1 on 2022-03-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_remove_workload_deploy_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadsystemconfig',
            name='component_param_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='component parameter id'),
        ),
    ]
