# Generated by Django 3.1.1 on 2022-03-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_auto_20220324_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='localjob',
            name='config_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='localjob',
            name='log_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
