# Generated by Django 3.1.1 on 2022-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_auto_20220325_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinstance',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
