# Generated by Django 3.1.1 on 2022-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_auto_20220328_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='localjob',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='job progress'),
        ),
        migrations.AlterField(
            model_name='localinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('FREE', 'FREE'), ('IN_USE', 'IN_USE')], default='FREE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='localjob',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_START', 'NOT_START'), ('IN_QUEUE', 'IN_QUEUE'), ('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], default='NOT_START', max_length=30, null=True),
        ),
    ]
