# Generated by Django 3.1.1 on 2022-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_auto_20220328_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localjob',
            options={'ordering': ['-id', 'status']},
        ),
        migrations.AddField(
            model_name='localjob',
            name='user',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
