# Generated by Django 3.1.1 on 2022-03-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_auto_20220328_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localjob',
            options={'ordering': ['-id', 'status']},
        ),
    ]
