# Generated by Django 3.1.1 on 2022-04-29 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0010_auto_20220329_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisonParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('parameter', models.CharField(blank=True, max_length=50, null=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
