# Generated by Django 3.1.1 on 2022-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_auto_20220426_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinstance',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
