# Generated by Django 3.1.1 on 2022-05-04 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_provisonparametervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisonparametervalue',
            name='realValues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
    ]
