# Generated by Django 3.1.1 on 2022-05-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0014_auto_20220505_1542'),
        ('local', '0012_provisonparametervalue_realvalues'),
    ]

    operations = [
    ]
