# Generated by Django 3.1.1 on 2022-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0015_merge_20220505_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localjob',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_START', 'NOT_START'), ('IN_QUEUE', 'IN_QUEUE'), ('RUNNING', 'RUNNING'), ('PROVISIONING', 'PROVISIONING'), ('PROVISION_FAILED', 'PROVISION_FAILED'), ('BENCHMARKING', 'BENCHMARKING'), ('BENCHMARK_FAILED', 'BENCHMARK_FAILED'), ('FAILED', 'FAILED'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], default='IN_QUEUE', max_length=30, null=True),
        ),
    ]
