# Generated by Django 3.1.1 on 2022-07-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0017_auto_20220509_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
