# Generated by Django 3.2.15 on 2022-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0020_auto_20220928_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinstance',
            name='internal_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
