# Generated by Django 3.2.15 on 2022-12-29 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0021_localinstance_internal_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinstance',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None),
        ),
    ]
