# Generated by Django 3.2.15 on 2022-12-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0022_localinstance_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinstance',
            name='ssh_port',
            field=models.PositiveIntegerField(blank=True, default=22, null=True),
        ),
    ]
