# Generated by Django 3.2.15 on 2023-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0023_localinstance_ssh_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalJobTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.CharField(blank=True, max_length=128, null=True)),
                ('test_cycle', models.CharField(blank=True, max_length=30, null=True)),
                ('commit', models.CharField(blank=True, max_length=30, null=True)),
                ('infra_type', models.CharField(blank=True, max_length=30, null=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('test_case', models.CharField(blank=True, max_length=128, null=True)),
                ('kpi_key', models.CharField(blank=True, max_length=256, null=True)),
                ('kpi_value', models.CharField(blank=True, max_length=50, null=True)),
                ('test_time', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_type', models.CharField(blank=True, max_length=30, null=True)),
                ('test_result', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAILED', 'FAILED'), ('NORUN', 'NORUN')], max_length=30, null=True)),
                ('failed_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('test_date', models.CharField(blank=True, max_length=50, null=True)),
                ('log_url', models.CharField(blank=True, max_length=512, null=True)),
                ('cumulus_uri', models.CharField(blank=True, max_length=512, null=True)),
                ('tag', models.CharField(blank=True, choices=[('PERFORMANCE', 'PERFORMANCE'), ('VALIDATION', 'VALIDATION'), ('FUNCTION', 'FUNCTION')], max_length=512, null=True)),
                ('jenkins_job_id', models.CharField(blank=True, max_length=30, null=True)),
                ('job_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('itr', models.CharField(blank=True, max_length=30, null=True)),
                ('test_from', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
