# Generated by Django 3.2.18 on 2023-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0024_localjobtestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localinstance',
            name='instance_type',
            field=models.CharField(blank=True, choices=[('ICX', 'ICX'), ('SPR', 'SPR')], default='SPR', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='localinstance',
            name='k8s_role',
            field=models.CharField(blank=True, choices=[('controller,worker', 'controller,worker'), ('controller', 'controller'), ('worker', 'worker')], default='controller,worker', max_length=30, null=True),
        ),
    ]
