# Generated by Django 3.2.19 on 2023-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0025_auto_20230516_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localjob',
            name='provision_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
