# Generated by Django 3.2.19 on 2023-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0026_alter_localjob_provision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localjobtestresult',
            name='jenkins_job_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
