# Generated by Django 3.2.19 on 2023-08-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0027_alter_localjobtestresult_jenkins_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='localinstance',
            name='occupant_job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
