# Generated by Django 3.2.19 on 2023-08-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0028_localinstance_occupant_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localjobtestresult',
            options={'ordering': ['-id']},
        ),
    ]
